background            {{colors.surface_container_lowest.default.hex}}
foreground            {{colors.on_surface.default.hex}}
cursor                {{colors.on_surface.default.hex}}

selection_background  {{colors.on_secondary_container.default.hex}}
selection_foreground  {{colors.secondary_container.default.hex}}

color0                {{colors.surface_container_lowest.default.hex}}
color1                {{colors.error.default.hex}}
color2                {{colors.tertiary.default.hex}}
color3                {{colors.secondary.default.hex}}
color4                {{colors.primary.default.hex}}
color5                {{colors.tertiary_fixed_dim.default.hex}}
color6                {{colors.secondary_fixed_dim.default.hex}}
color7                {{colors.on_surface.default.hex}}

color8                {{colors.surface_variant.default.hex}}
color9                {{colors.error_container.default.hex}}
color10               {{colors.tertiary_container.default.hex}}
color11               {{colors.secondary_container.default.hex}}
color12               {{colors.primary_container.default.hex}}
color13               {{colors.tertiary_container.default.hex}}
color14               {{colors.secondary_container.default.hex}}
color15               {{colors.on_surface_variant.default.hex}}

# --- Starship Prompt Bubbles ---
color255              {{colors.primary_container.default.hex}}
color240              {{colors.on_primary_container.default.hex}}
color252              {{colors.secondary_container.default.hex}}
color235              {{colors.on_secondary_container.default.hex}}
color243              {{colors.primary.default.hex}}
color244              {{colors.error.default.hex}}
color245              {{colors.outline_variant.default.hex}}
color232              {{colors.on_primary.default.hex}}
color233              {{colors.on_primary_container.default.hex}}
color234              {{colors.on_secondary.default.hex}}
color236              {{colors.on_tertiary.default.hex}}
color237              {{colors.on_tertiary_container.default.hex}}
color238              {{colors.on_error.default.hex}}
color239              {{colors.on_error_container.default.hex}}
